"""Cascade deleting for tasks and tags

Revision ID: 1269befcf089
Revises: 885298e6e4c4
Create Date: 2025-05-17 15:04:26.777669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1269befcf089"
down_revision: Union[str, None] = "885298e6e4c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "task_tag_association_task_id_fkey", "task_tag_association", type_="foreignkey"
    )
    op.drop_constraint(
        "task_tag_association_tag_id_fkey", "task_tag_association", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "task_tag_association", "tasks", ["task_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "task_tag_association", "tags", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_tag_association", type_="foreignkey")
    op.drop_constraint(None, "task_tag_association", type_="foreignkey")
    op.create_foreign_key(
        "task_tag_association_tag_id_fkey",
        "task_tag_association",
        "tags",
        ["tag_id"],
        ["id"],
    )
    op.create_foreign_key(
        "task_tag_association_task_id_fkey",
        "task_tag_association",
        "tasks",
        ["task_id"],
        ["id"],
    )
    # ### end Alembic commands ###
