"""Set ondelete values for project models

Revision ID: 2cbd29b9e442
Revises: 16e9ebf5f2da
Create Date: 2025-05-25 15:36:03.098014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbd29b9e442'
down_revision: Union[str, None] = '16e9ebf5f2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_members_user_id_fkey', 'project_members', type_='foreignkey')
    op.drop_constraint('project_members_project_id_fkey', 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key('project_members_project_id_fkey', 'project_members', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_members_user_id_fkey', 'project_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
